### ISSUE TITLE
Where is the code ?

### ISSUE THREAD

**Issue by The-Real-Thisas** [Raymo111/voiceprint#1]
Forgive me if I'm wrong but I can't seem to find the actual module or any install instructions ? 

The linked repo doesn't appear to be a pam module so ? 

Was this a WIP what just never actually got created ?

**Comment by Raymo111** [comment]
This is a WIP project. I created the repo and website some time ago and never got around to it. There's a high likelihood that I'm going to work on this at @hackthenorth this year 🙂

Check back in late September and it should work!

**Comment by The-Real-Thisas** [comment]
Ah, would be kinda helpful if that was mentioned in the readme or something since the website and the repo give the impression that this is a legacy project that just isn't maintained anymore. I was pretty confused and thought maybe I was using github wrong or something. 

Best of luck if you do end up building this project out.

**Comment by Raymo111** [comment]
Honestly, I didn't expect anyone to even find this repo :)
I've just committed a note in the README that this project has yet to be built.
Thanks for the encouragement!

**Comment by Raymo111** [comment]
Code is up :)

**Comment by The-Real-Thisas** [comment]
@Raymo111 Sick I'll test it out later.
